m000355/Models/product.cs
namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public class product
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [StringLength(64)]
        public string guid { get; set; }

        public string title { get; set; }
        [Key]
        [Column(Order = 0)]
        public string subtitle { get; set; }

        public DateTime? isComingSoon { get; set; }

        public string product_description { get; set; }

        public string emblem { get; set; }
        public string emblem_alt { get; set; }
        public string product_features { get; set; }
        public string featurespic { get; set; }

        public string featurespic_alt { get; set; }
        public string downloadfile { get; set; }

        public string downloadfile_alt { get; set; }

        public string product_specification { get; set; }

        public string download { get; set; }
        public string pic { get; set; }

        public string pic_alt { get; set; }
        public string videoLink { get; set; }
        public int? sortIndex { get; set; }
        [StringLength(1)]
        public string status { get; set; }

        public DateTime? create_date { get; set; }

        public DateTime? modifydate { get; set; }
        public string create_name { get; set; }
        public string modify_name { get; set; }
        [Key]
        [Column(Order = 1)]
        [StringLength(30)]
        public string lang { get; set; }
        public string productsCategory_guid { get; set; }
        public string productsSubClass_guid { get; set; }
        public string option { get; set; }
        public string option_alt { get; set; }
        public string specColumn { get; set; }
        public string specValue { get; set; }
        public string keywords { get; set; }

        public string description { get; set; }
    }
}

m000355/Controllers/ProductsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Models;
using web.Repository;
using Web.Models;
using Web.Service;

namespace m000355.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            if (Session["WordLang"] == null)
            {
                Session["WordLang"] = "en";
                Session["WholeLang"] = "EN";
            }

            string wholeLang = Session["WordLang"].ToString();
            if (wholeLang == null)
            {
                wholeLang = "en";
            }

            Model DB = new Model();

            var privacyData = (from a in DB.web_data
                               where a.lang == wholeLang
                               select a).FirstOrDefault();
            ViewBag.privacyData = privacyData.privacypolicy;

            if (privacyData != null)
            {
                ViewBag.description = privacyData.description_products;
                ViewBag.keywords = privacyData.keywords_products;
            }
            else
            {
                ViewBag.description = "";
                ViewBag.keywords = "";
            }

            var productBanner = (from a in DB.product_banner
                                 where a.status == "Y" && a.lang == wholeLang && a.type == "yes"
                                 select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productBanner = productBanner;
            var productBannerNoPic = (from a in DB.product_banner
                                      where a.status == "Y" && a.lang == wholeLang && a.type == "no"
                                      select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productBannerNoPic = productBannerNoPic;

            List<product_subclass> psFirst = new List<product_subclass>();
            var productCatalogFirst = (from a in DB.product_category
                                       where a.status == "Y" && a.lang == wholeLang
                                       select a).OrderBy(x => x.sortIndex).ToList();

            foreach (var tempItem in productCatalogFirst)
            {
                var tempProductSubclassFirst = (from a in DB.product_subclass
                                                where a.productsCategory_guid == tempItem.guid && a.status == "Y" && a.lang == wholeLang && a.category == "0"
                                                select a).FirstOrDefault();
                psFirst.Add(tempProductSubclassFirst);
            }
            var productSubclassFirst = (from a in DB.product_subclass
                                        where a.status == "Y" && a.lang == wholeLang && a.category == "0"
                                        select a).ToList();
            ViewBag.productSubclassFirst = psFirst;
            //ViewBag.productSubclassFirst = productSubclassFirst;

            //var productSubclassFirst = (from a in DB.product_subclass
            //                            where a.status == "Y" && a.lang == wholeLang && a.category == "0"
            //                            select a).OrderBy(x => x.sortIndex).ToList();
            //ViewBag.productSubclassFirst = productSubclassFirst;

            var productSubclassMultiLevel = (from a in DB.product_subclass
                                             where a.status == "Y" && a.lang == wholeLang && a.category != "0"
                                             select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productSubclassMultiLevel = productSubclassMultiLevel;

            var webBasicData = (from a in DB.web_data
                                where a.lang == wholeLang
                                select a).FirstOrDefault();
            ViewBag.webBasicData = webBasicData;

            var defaultcatalogguid = (from a in DB.dealer_catalog
                                      where a.lang == wholeLang && a.status == "Y"
                                      select a).OrderBy(x => x.sortIndex).ToList();

            NameValueCollection langData = new NameValueCollection();
            if (wholeLang == "tw")
            {
                langData = FunctionService.getLangData("tw");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "特色";
                //ViewBag.specificationsTab = "規格";
                //ViewBag.downloadTab = "下載";
                //ViewBag.searchkeyword = "關鍵字...";
                //ViewBag.searchResults = "個結果被找到關於";
                //ViewBag.searchAbout = "大約";
                //ViewBag.openRfq = "前往詢價";
                //ViewBag.saveRfq = "儲存詢價";
                ViewBag.lang = "tw";
                //ViewBag.reqRfq = "詢價";
                //ViewBag.aboutus = "關於我們";
                //ViewBag.productpage = "產品專區";
                //ViewBag.warranty = "保修專區";
                //ViewBag.contactus = "聯絡我們";
                //ViewBag.catalogdownload = "型錄下載";
                //ViewBag.dealer = "經銷商區";
                //ViewBag.latestnews = "最新消息";
                //ViewBag.readmore = "瀏覽更多";
                //ViewBag.privacyPolicy = "隱私政策";
                //ViewBag.quotation = "詢問表單";
                //ViewBag.productDesc = "DUROFIX是21世紀的新品牌，目前正在歐洲、美洲、澳大利亞和亞洲推廣。";
                //ViewBag.homepage = "首頁";
                //ViewBag.productCategoryBtn = "產品類別";
                //ViewBag.productListBtn = "產品列表";
                //ViewBag.productsSearch = "產品搜尋";
                //ViewBag.productSearchBtn = "產品搜尋";
                //ViewBag.terms = "條款";
                //ViewBag.registered = "商標";
                //ViewBag.inquire = "詢問";
                //ViewBag.information = "資訊";
                //ViewBag.contactform = "聯絡表單";
                //ViewBag.footerbrand = "品牌";
                //ViewBag.footergroup = "群組";
                //ViewBag.whychose = "為何選擇";
                //ViewBag.offlinepage = "網站維護中";
                //ViewBag.offlinemobilepage = "頁面維護中，請於稍後重整頁面";
                //ViewBag.completeall = "請填寫所有項目";
                //ViewBag.assure = "以確保正確回復";
                //ViewBag.businessType = "商業類型";
                //ViewBag.companyName = "公司名稱";
                //ViewBag.contactName = "聯絡人";
                //ViewBag.email = "電子郵件";
                //ViewBag.tel = "電話";
                //ViewBag.country = "國家";
                //ViewBag.address = "地址";
                //ViewBag.website = "網址";
                //ViewBag.subject = "主題";
                //ViewBag.leaveMessage = "留下您的訊息";
                //ViewBag.verification = "驗證碼";
                //ViewBag.submit = "提交";
            }
            else if (wholeLang == "en")
            {
                langData = FunctionService.getLangData("en");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "Features";
                //ViewBag.specificationsTab = "Specifications";
                //ViewBag.downloadTab = "Download";
                //ViewBag.searchkeyword = "Keyword...";
                //ViewBag.searchResults = " results found for ";
                //ViewBag.searchAbout = "About";
                //ViewBag.openRfq = "OPEN RFQ";
                //ViewBag.saveRfq = "Saved to Request for Quotation";
                ViewBag.lang = "en";
                //ViewBag.reqRfq = "REQUEST FOR QUOTATION";
                //ViewBag.aboutus = "ABOUT US";
                //ViewBag.productpage = "PRODUCTS";
                //ViewBag.warranty = "WARRANTY";
                //ViewBag.contactus = "CONTACT US";
                //ViewBag.catalogdownload = "CATALOG DOWNLOAD";
                //ViewBag.dealer = "DEALER";
                //ViewBag.latestnews = "LATEST NEWS";
                //ViewBag.readmore = "READ MORE";
                //ViewBag.privacyPolicy = "PRIVACY POLICY";
                //ViewBag.quotation = "Request for Quotation";
                //ViewBag.productDesc = "DUROFIX™ is a new brand for the 21st century, and is currently being promoted in Europe, America, Australia, and Asia.";
                //ViewBag.homepage = "HOME";
                //ViewBag.productCategoryBtn = "Product Category";
                //ViewBag.productListBtn = "Product List";
                //ViewBag.productsSearch = "Products Search";
                //ViewBag.productSearchBtn = "PRODUCT SEARCH";
                //ViewBag.terms = "TERMS";
                //ViewBag.registered = "REGISTERED";
                //ViewBag.inquire = "INQUIRE";
                //ViewBag.information = "INFORMATION";
                //ViewBag.contactform = "CONTACT FORM";
                //ViewBag.footerbrand = "BRAND";
                //ViewBag.footergroup = "GROUP";
                //ViewBag.whychose = "WHY CHOOSE DUROFIX";
                //ViewBag.offlinepage = "The Website is Under Maintenance";
                //ViewBag.offlinemobilepage = "This page is down for maintenance. We are working to get it back up and running as soon as possible. Please check back!";
                //ViewBag.completeall = "Please complete all item with";
                //ViewBag.assure = "to assure proper response";
                //ViewBag.businessType = "Business Type";
                //ViewBag.companyName = "Company Name";
                //ViewBag.contactName = "Contact Name";
                //ViewBag.email = "E-mail";
                //ViewBag.tel = "TEL";
                //ViewBag.country = "Country";
                //ViewBag.address = "Address";
                //ViewBag.website = "Web Site";
                //ViewBag.subject = "Subject";
                //ViewBag.leaveMessage = "Leave Your Message";

m000355/Views/Products/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wp" id="index">
    <main class="main">
        <div class="productsTitle blank">
            <h1 class="mainTitle kanit font-80 font-weight-600" data-aos="fade-up" data-aos-delay="300">@ViewBag.ResLang["productpage"]</h1>
            <div class="text kanit font-20 font-weight-500 text-uppercase text-646464" data-aos="fade-up" data-aos-delay="500">@ViewBag.ResLang["productDesc"]</div>
            <a href="@Url.Action("RFQ", "Products")" class="RFQBox flex-align-center" data-aos="fade-left" data-aos-delay="700">
                <img src="~/styles/images/layout/rfq.svg" alt="">
                <span class="kanit font-20 font-weight-500 text-646464">@ViewBag.ResLang["quotation"]</span>
                @if (Session["WordLang"].ToString() == "en")
                {
                    <span class="qty kanit font-20 font-weight-500 flex-center">@Session["InquiryNumEn"]</span>
                }
                else if (Session["WordLang"].ToString() == "tw")
                {
                    <span class="qty kanit font-20 font-weight-500 flex-center">@Session["InquiryNumTw"]</span>
                }
                else
                {
                    <span class="qty kanit font-20 font-weight-500 flex-center">@Session["InquiryNumEn"]</span>
                }
            </a>
        </div>
        <div class="indexProduct pt-4">
            @if (ViewBag.productBanner != null)
            {
                foreach (var item in ViewBag.productBanner)
                {
                    var tempPic = item.pic.Substring(1);
                    var temppicMobile = item.picmobile.Substring(1);
                    <div class="indexProductItem">
                        <div class="indexProductItemBg background-cover d-none d-sm-block" style="background-image: url(@tempPic);"></div>
                        <div class="indexProductItemBg background-cover d-sm-none" style="background-image: url(@temppicMobile);"></div>
                        <div class="indexProductInner">
                            <h2 class="title kanit font-40 font-weight-600 text-fff" data-aos="fade-up" data-aos-delay="300">@item.title</h2>
                            <div class="text roboto font-16 font-weight-500 text-fff text-uppercase" data-aos="fade-up" data-aos-delay="500">@item.subtitle </div>
                            <div data-aos="fade-right" data-aos-delay="700">
                                <a href="~/products/productlist?category=@item.category" class="mainBtn">@ViewBag.ResLang["readmore"]</a>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
        <div class="produtsLast">
            @if (ViewBag.productBannerNoPic != null)
            {
                foreach (var itemNo in ViewBag.productBannerNoPic)
                {
                    <div class="productsLastItem">
                        <h2 class="title kanit font-40 font-weight-600 text-fff" data-aos="fade-up" data-aos-delay="300">@itemNo.title</h2>
                        <div class="text roboto font-16 font-weight-400 text-fff" data-aos="fade-up" data-aos-delay="500">@itemNo.subtitle</div>
                        <div data-aos="fade-right" data-aos-delay="700">
                            <a href="~/products/productlist?category=@itemNo.category" class="mainBtn">@ViewBag.ResLang["readmore"]</a>
                        </div>
                    </div>
                }
            }
        </div>
    </main>
</div>

m000355/Views/Products/RFQ.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="wp" id="RFQ">
    <main class="main">
        <div class="breadcrumbBlock blank">
            <div class="breadcrumbWrap RFQ-breadcrumbWrap">
                <a href="~/products" class="breadcrumbBack">
                    <span class="backIcon flex-center"><i class="icon-arrow"></i></span>
                    <span class="kanit font-weight-600 text-323232">@ViewBag.ResLang["productCategoryBtn"]</span>
                </a>
                <div class="breadcrumbInner">
                    <ol class="breadcrumb kanit font-weight-400 text-323232">
                        <li class="breadcrumb-item"><a href="#">@ViewBag.ResLang["homepage"]</a></li>
                        <li class="breadcrumb-item"><a href="#">@ViewBag.ResLang["productpage"]</a></li>
                        <li class="breadcrumb-item"><a href="#">@ViewBag.ResLang["quotation"]</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="RFQMainBlock blank">
            <div class="RFQMainWrap blank">
                <div class="RFQTitle">
                    <h1 class="mainTitle kanit font-60 font-weight-600 text-323232 text-uppercase" data-aos="fade-up" data-aos-delay="300">@ViewBag.ResLang["quotation"]</h1>
                    <h2 class="text kanit font-20 font-weight-500 text-646464 text-uppercase" data-aos="fade-up" data-aos-delay="500">@ViewBag.ResLang["productDesc"] </h2>
                </div>
                <div class="RFQList">
                    <div data-aos="fade-left" data-aos-delay="300" data-aos-duration="600">
                        @if (Session["WordLang"].ToString() == "en")
                        {
                            if ((Session["InquiryEn"] as List<Dictionary<string, string>>) != null)
                            {
                                foreach (var item in (Session["InquiryEn"] as List<Dictionary<string, string>>))
                                {


                                    @*<a href="productdetial?id=@item["ProductGuid"]" class="RFQItem">
                                            <span class="RFQItemImg">
                                                <img src="@Url.Content("~" + item["Pic"])" alt="">
                                            </span>
                                            <span class="RFQItemName">
                                                <span class="name d-block kanit font-20 font-weight-600 text-FCAE07 text-uppercase lh14">@item["ProductName"]</span>
                                                <span class="num d-block kanit font-16 font-weight-500 text-969696">@item["ProductSubName"]</span>

                                            </span>
                                            <span class="RFQItemDel"></span>
                                        </a>*@
                                    if (item.Count != 0)
                                    {
                                        <div class="RFQItem">
                                            <a href="productdetial?id=@item["ProductGuid"]" class="RFQItemImg">
                                                <img src="@Url.Content("~" + item["Pic"])" alt="">
                                            </a>
                                            <a href="productdetial?id=@item["ProductGuid"]" class="RFQItemName">
                                                <span class="name d-block kanit font-20 font-weight-600 text-FCAE07 text-uppercase lh14">@item["ProductName"]</span>
                                                <span class="num d-block kanit font-16 font-weight-500 text-969696">@item["ProductSubName"]</span>

                                            </a>
                                            <a href="@Url.Action("DeleteInquiry", "Products",new {  guid = @item["ProductGuid"]})">
                                                <div class="RFQItemDel cursor">
                                                </div>
                                            </a>
                                        </div>
                                    }

                                }
                            }
                        }
                        else if (Session["WordLang"].ToString() == "tw")
                        {
                            if ((Session["InquiryTw"] as List<Dictionary<string, string>>) != null)
                            {
                                foreach (var item in (Session["InquiryTw"] as List<Dictionary<string, string>>))
                                {
                                    <div class="RFQItem">
                                        <a href="productdetial?id=@item["ProductGuid"]" class="RFQItemImg">
                                            <img src="@Url.Content("~" + item["Pic"])" alt="">
                                        </a>
                                        <a href="productdetial?id=@item["ProductGuid"]" class="RFQItemName">
                                            <span class="name d-block kanit font-20 font-weight-600 text-FCAE07 text-uppercase lh14">@item["ProductName"]</span>
                                            <span class="num d-block kanit font-16 font-weight-500 text-969696">@item["ProductSubName"]</span>

                                        </a>
                                        <a href="@Url.Action("DeleteInquiry", "Products",new {  guid = @item["ProductGuid"]})">
                                            <div class="RFQItemDel cursor">
                                            </div>
                                        </a>
                                    </div>
                                }
                            }
                        }
                        else
                        {
                            if ((Session["InquiryEn"] as List<Dictionary<string, string>>) != null)
                            {
                                foreach (var item in (Session["InquiryEn"] as List<Dictionary<string, string>>))
                                {
                                    <div class="RFQItem">
                                        <a href="productdetial?id=@item["ProductGuid"]" class="RFQItemImg">
                                            <img src="@Url.Content("~" + item["Pic"])" alt="">
                                        </a>
                                        <a href="productdetial?id=@item["ProductGuid"]" class="RFQItemName">
                                            <span class="name d-block kanit font-20 font-weight-600 text-FCAE07 text-uppercase lh14">@item["ProductName"]</span>
                                            <span class="num d-block kanit font-16 font-weight-500 text-969696">@item["ProductSubName"]</span>

                                        </a>
                                        <a href="@Url.Action("DeleteInquiry", "Products",new {  guid = @item["ProductGuid"]})">
                                            <div class="RFQItemDel cursor">
                                            </div>
                                        </a>
                                    </div>
                                }
                            }
                        }

                    </div>
                </div>
                <div class="RFQFormBox" data-aos="fade-up" data-aos-delay="500" data-aos-duration="600">
                    <div class="hint kanit font-18">@ViewBag.ResLang["completeall"]<span class="text-red">*</span>@ViewBag.ResLang["assure"]</div>
                    <form action="@Url.Content("~/products/Send")" method="post" id="RFQForm" class="RFQForm">
                        @Html.AntiForgeryToken()
                        <div class="field-group">
                            <label class="label" for="bType">@ViewBag.ResLang["businessType"]<span class="text-red">*</span></label>
                            @*<v-select :options="optionsType" v-model="selectedType" :clearable="false" :searchable="false" id="bType"></v-select>*@
                            <select class="selectpicker" id="bType" name="bType">
                                <option>Importer</option>
                                <option>Distributor</option>
                                <option>Wholesaler</option>
                                <option>Retailer</option>
                                <option>Manufacturer</option>
                                <option>Others</option>
                            </select>
                        </div>
                        <div class="field-group half">
                            <label class="label" for="corp">@ViewBag.ResLang["companyName"]<span class="text-red">*</span></label>
                            <input class="input" type="text" id="corp" name="corp" required>
                        </div>
                        <div class="field-group half">
                            <label class="label" for="name">@ViewBag.ResLang["contactName"]<span class="text-red">*</span></label>
                            <input class="input" type="text" id="name" name="name" required>
                        </div>
                        <div class="field-group half">
                            <label class="label" for="email">@ViewBag.ResLang["email"]<span class="text-red">*</span></label>
                            <input class="input" type="email" id="email" name="email" required>
                        </div>
                        <div class="field-group half">
                            <label class="label" for="tel">@ViewBag.ResLang["tel"]<span class="text-red">*</span></label>
                            <input class="input" type="tel" id="tel" name="tel" required>
                        </div>
                        <div class="field-group p350">
                            <label class="label" for="country">@ViewBag.ResLang["country"]<span class="text-red">*</span></label>
                            @*<v-select :options="optionsCountry" v-model="selectedCountry" :clearable="false" :searchable="false" id="country"></v-select>*@
                            <select class="selectpicker" id="country" name="country">
                                <option>Taiwan</option>
                                <option>USA</option>
                                <option>UK</option>
                            </select>
                        </div>
                        <div class="field-group p640">
                            <label class="label" for="adress">@ViewBag.ResLang["address"]</label>
                            <input class="input" type="text" id="adress" name="adress">
                        </div>
                        <div class="field-group">
                            <label class="label" for="web">@ViewBag.ResLang["website"]</label>
                            <input class="input" type="text" id="web" name="web">
                        </div>
                        <div class="field-group">
                            <label class="label" for="subject">@ViewBag.ResLang["subject"]<span class="text-red">*</span></label>
                            @*<v-select :options="optionsSubject" v-model="selectedSubject" :clearable="false" :searchable="false" id="subject"></v-select>*@
                            <select class="selectpicker" id="subject" name="subject">
                                @if (ViewBag.contactSubjectData != null)
                                {
                                    foreach (var item in ViewBag.contactSubjectData)
                                    {
                                        <option>@item</option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="field-group textareaGroup">
                            <label class="label textareaLabel" for="content">@ViewBag.ResLang["leaveMessage"]</label>
                            <textarea class="input textarea" id="content" name="content" placeholder=""></textarea>
                        </div>
                        <div class="field-group p445">
                            <label class="label" for="vcode">@ViewBag.ResLang["verification"]<span class="text-red">*</span></label>
                            <input class="input" type="text" id="vcode" name="vcode" required>
                        </div>
                        <div class="v-code">
                            <img id="captcha" onclick="reloadCaptcha()" src="@Url.Content("~/Content/BuildCaptcha.aspx")" alt="">
                        </div>
                        <div class="submitWrap">
                            <button class="submit flex-center kanit font-18 font-weight-500" type="submit">
                                <span class="d-block">@ViewBag.ResLang["submit"]</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </main>
</div>

@section scripts {
    <script>
        //重製驗證碼
        function reloadCaptcha() {
            $('#captcha').attr('src', $('#captcha').attr('src') + "?d=" + Date.now());
        }

        function handleCancel(productid) {
            console.log(productid);
            @*$.ajax({
                type: 'POST',
                url: '@Url.Action("deleteToProductInquery", "Ajax")',
                data: { productid: productid },
                success: function (data) {
                    location.reload();
                }
            });*@
        }
    </script>
}

m000355/Views/Products/RFQSend.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wp" id="index">
    <main class="main">
        <div id="RFQ-send">
            <div class="breadcrumbBlock blank">
                <div class="breadcrumbWrap">
                    <a href="@Url.Action("Index", "Products")" class="breadcrumbBack">
                        <span class="backIcon flex-center"><i class="icon-arrow"></i></span>
                        <span class="kanit font-weight-600 text-323232">Product Category</span>
                    </a>
                    <div class="breadcrumbInner">
                        <ol class="breadcrumb kanit font-weight-400 text-323232">
                            <li class="breadcrumb-item"><a href="./">HOME</a></li>
                            <li class="breadcrumb-item"><a href="@Url.Action("Index", "Products")">PRODUCTS</a></li>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="RFQSendBlock blank">
                <div class="RFQSendInner">
                    <div class="RFQSendIcon">
                        <div class="iconBox">
                            <img src="@Url.Content("~/styles/images/product/saved-ring.svg")" alt="" class="ring">
                            <img src="@Url.Content("~/styles/images/product/check.svg")" alt="" class="check">
                        </div>
                    </div>
                    <h1 class="RFQSendTitle kanit font-40 font-weight-600 text-323232 text-uppercase" data-aos="fade-up" data-aos-delay="300">Your message was sent successfully.</h1>
                    <h2 class="RFQSendText kanit font-20 font-weight-500 text-646464" data-aos="fade-up" data-aos-delay="500">Thank you so much for your submission. We’ll be in touch shortly.</h2>
                    <div data-aos="fade-right" data-aos-delay="700">
                        <a href="./" class="RFQSendBtn flex-center kanit font-18 font-weight-500">OK</a>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>