m000355/Models/abouts.cs
namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public class abouts
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(64)]
        public string guid { get; set; }

        public string title { get; set; }

        public string notes { get; set; }

        public string content { get; set; }


        public DateTime? modifydate { get; set; }

        [StringLength(1)]
        public string status { get; set; }

        public DateTime? create_date { get; set; }
        public string create_name { get; set; }
        public string modify_name { get; set; }


        [StringLength(30)]
        public string lang { get; set; }

        public string seo_keywords { get; set; }

        public string seo_description { get; set; }
    }
}

m000355/Models/group.cs
namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public class group
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(64)]
        public string guid { get; set; }

        public string title { get; set; }

        public string notes { get; set; }

        public string content { get; set; }


        public DateTime? modifydate { get; set; }

        [StringLength(1)]
        public string status { get; set; }

        public DateTime? create_date { get; set; }
        public string create_name { get; set; }
        public string modify_name { get; set; }


        [StringLength(30)]
        public string lang { get; set; }

        public string seo_keywords { get; set; }

        public string seo_description { get; set; }
    }
}

m000355/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.Service;

namespace m000355.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            if (Session["WordLang"] == null)
            {
                Session["WordLang"] = "en";
                Session["WholeLang"] = "EN";
            }

            string wholeLang = Session["WordLang"].ToString();
            if (wholeLang == null)
            {
                wholeLang = "en";
            }

            Model DB = new Model();

            var privacyData = (from a in DB.web_data
                               where a.lang == wholeLang
                               select a).FirstOrDefault();
            ViewBag.privacyData = privacyData.privacypolicy;

            var productSubclassFirst = (from a in DB.product_subclass
                                        where a.status == "Y" && a.lang == wholeLang && a.category == "0"
                                        select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productSubclassFirst = productSubclassFirst;

            var productSubclassMultiLevel = (from a in DB.product_subclass
                                             where a.status == "Y" && a.lang == wholeLang && a.category != "0"
                                             select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productSubclassMultiLevel = productSubclassMultiLevel;

            var brandData = (from a in DB.abouts
                             where a.lang == wholeLang && a.status == "Y"
                             select a).FirstOrDefault();
            if (brandData != null)
            {
                ViewBag.brandData = brandData.content;
                ViewBag.description = brandData.seo_description;
                ViewBag.keywords = brandData.seo_keywords;
            }
            else
            {
                ViewBag.description = "";
                ViewBag.keywords = "";
            }

            var webBasicData = (from a in DB.web_data
                                where a.lang == wholeLang
                                select a).FirstOrDefault();
            ViewBag.webBasicData = webBasicData;

            var defaultcatalogguid = (from a in DB.dealer_catalog
                                      where a.lang == wholeLang && a.status == "Y"
                                      select a).OrderBy(x => x.sortIndex).ToList();
            
            NameValueCollection langData = new NameValueCollection();
            if (wholeLang == "tw")
            {
                langData = FunctionService.getLangData("tw");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "特色";
                //ViewBag.specificationsTab = "規格";
                //ViewBag.downloadTab = "下載";
                //ViewBag.searchkeyword = "關鍵字...";
                //ViewBag.searchResults = "個結果被找到關於";
                //ViewBag.searchAbout = "大約";
                //ViewBag.openRfq = "前往詢價";
                //ViewBag.saveRfq = "儲存詢價";
                //ViewBag.productsSearch = "產品搜尋";
                ViewBag.lang = "tw";
                //ViewBag.reqRfq = "詢價";
                //ViewBag.aboutus = "關於我們";
                //ViewBag.productpage = "產品專區";
                //ViewBag.warranty = "保修專區";
                //ViewBag.contactus = "聯絡我們";
                //ViewBag.catalogdownload = "型錄下載";
                //ViewBag.dealer = "經銷商區";
                //ViewBag.latestnews = "最新消息";
                //ViewBag.readmore = "瀏覽更多";
                //ViewBag.privacyPolicy = "隱私政策";
                //ViewBag.quotation = "詢問表單";
                //ViewBag.productDesc = "DUROFIX是21世紀的新品牌，目前正在歐洲、美洲、澳大利亞和亞洲推廣。";
                //ViewBag.homepage = "首頁";
                //ViewBag.productCategoryBtn = "產品類別";
                //ViewBag.productListBtn = "產品列表";
                //ViewBag.productSearchBtn = "產品搜尋";
                //ViewBag.terms = "條款";
                //ViewBag.registered = "商標";
                //ViewBag.inquire = "詢問";
                //ViewBag.information = "資訊";
                //ViewBag.contactform = "聯絡表單";
                //ViewBag.footerbrand = "品牌";
                //ViewBag.footergroup = "群組";
                //ViewBag.whychose = "為何選擇";
                //ViewBag.offlinepage = "網站維護中";
                //ViewBag.offlinemobilepage = "頁面維護中，請於稍後重整頁面";
                //ViewBag.completeall = "請填寫所有項目";
                //ViewBag.assure = "以確保正確回復";
                //ViewBag.businessType = "商業類型";
                //ViewBag.companyName = "公司名稱";
                //ViewBag.contactName = "聯絡人";
                //ViewBag.email = "電子郵件";
                //ViewBag.tel = "電話";
                //ViewBag.country = "國家";
                //ViewBag.address = "地址";
                //ViewBag.website = "網址";
                //ViewBag.subject = "主題";
                //ViewBag.leaveMessage = "留下您的訊息";
                //ViewBag.verification = "驗證碼";
                //ViewBag.submit = "提交";
                //ViewBag.aboutmoregroup = "企業沿革";
            }
            else if (wholeLang == "en")
            {
                langData = FunctionService.getLangData("en");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "Features";
                //ViewBag.specificationsTab = "Specifications";
                //ViewBag.downloadTab = "Download";
                //ViewBag.searchkeyword = "Keyword...";
                //ViewBag.searchResults = " results found for ";
                //ViewBag.searchAbout = "About";
                //ViewBag.openRfq = "OPEN RFQ";
                //ViewBag.saveRfq = "Saved to Request for Quotation";
                //ViewBag.productsSearch = "Products Search";
                ViewBag.lang = "en";
                //ViewBag.reqRfq = "REQUEST FOR QUOTATION";
                //ViewBag.aboutus = "ABOUT US";
                //ViewBag.productpage = "PRODUCTS";
                //ViewBag.warranty = "WARRANTY";
                //ViewBag.contactus = "CONTACT US";
                //ViewBag.catalogdownload = "CATALOG DOWNLOAD";
                //ViewBag.dealer = "DEALER";
                //ViewBag.latestnews = "LATEST NEWS";
                //ViewBag.readmore = "READ MORE";
                //ViewBag.privacyPolicy = "PRIVACY POLICY";
                //ViewBag.quotation = "Request for Quotation";
                //ViewBag.productDesc = "DUROFIX™ is a new brand for the 21st century, and is currently being promoted in Europe, America, Australia, and Asia.";
                //ViewBag.homepage = "HOME";
                //ViewBag.productCategoryBtn = "Product Category";
                //ViewBag.productListBtn = "Product List";
                //ViewBag.productSearchBtn = "PRODUCT SEARCH";
                //ViewBag.terms = "TERMS";
                //ViewBag.registered = "REGISTERED";
                //ViewBag.inquire = "INQUIRE";
                //ViewBag.information = "INFORMATION";
                //ViewBag.contactform = "CONTACT FORM";
                //ViewBag.footerbrand = "BRAND";
                //ViewBag.footergroup = "GROUP";
                //ViewBag.whychose = "WHY CHOOSE DUROFIX";
                //ViewBag.offlinepage = "The Website is Under Maintenance";
                //ViewBag.offlinemobilepage = "This page is down for maintenance. We are working to get it back up and running as soon as possible. Please check back!";
                //ViewBag.completeall = "Please complete all item with";
                //ViewBag.assure = "to assure proper response";
                //ViewBag.businessType = "Business Type";
                //ViewBag.companyName = "Company Name";
                //ViewBag.contactName = "Contact Name";
                //ViewBag.email = "E-mail";
                //ViewBag.tel = "TEL";
                //ViewBag.country = "Country";
                //ViewBag.address = "Address";
                //ViewBag.website = "Web Site";
                //ViewBag.subject = "Subject";
                //ViewBag.leaveMessage = "Leave Your Message";
                //ViewBag.verification = "Verification code";
                //ViewBag.submit = "SUBMIT";
                //ViewBag.aboutmoregroup = "ABOUT MORE GROUP";
            }
            else if (wholeLang == "cn")
            {
                langData = FunctionService.getLangData("cn");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                if (defaultcatalogguid.Count() == 0)
                {
                    ViewBag.defaultcatalogguid = "";
                }
                else
                {
                    ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                }

                ViewBag.lang = "cn";
            }
            else
            {
                langData = FunctionService.getLangData("en");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                //ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "Features";
                //ViewBag.specificationsTab = "Specifications";
                //ViewBag.downloadTab = "Download";
                //ViewBag.searchkeyword = "Keyword...";
                //ViewBag.searchResults = " results found for ";
                //ViewBag.searchAbout = "About";
                //ViewBag.openRfq = "OPEN RFQ";
                //ViewBag.saveRfq = "Saved to Request for Quotation";
                //ViewBag.productsSearch = "Products Search";
                ViewBag.lang = "en";
                //ViewBag.reqRfq = "REQUEST FOR QUOTATION";

m000355/Views/About/Group.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wp" id="index">
    <main class="main group">
        <div id="group">
            <div class="pageBannerBlock blank" style="background-image: url(@Url.Content("~/styles/images/about/about-banner.jpg"));">
                <div class="breadcrumbInner">
                    <ol class="breadcrumb kanit font-weight-400">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">@ViewBag.ResLang["homepage"]</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "About")">@ViewBag.ResLang["aboutus"]</a></li>
                        <li class="breadcrumb-item" aria-current="page">@ViewBag.ResLang["aboutmoregroup"]</li>
                    </ol>
                </div>
                <div class="pageTitle">
                    <h1 class="kanit font-80 font-weight-600" data-aos="fade-up">@ViewBag.ResLang["aboutus"]</h1>
                </div>
                <div class="tagsWrap kanit font-weight-600 font-18 unblank">
                    <div class="tagBox active">
                        <a href="@Url.Action("Index", "About")">@ViewBag.ResLang["footerbrand"]</a>
                    </div>
                    <div class="tagBox">
                        <a href="@Url.Action("Group", "About")">@ViewBag.ResLang["aboutmoregroup"]</a>
                    </div>
                </div>
            </div>
            <div class="groupMainBlock blank">
                @if (ViewBag.groupData != null)
                {
                    @Html.Raw(ViewBag.groupData)
                }
                @*<div class="groupMainInner text-646464 roboto font-16">
                        <h2 class="kanit font-30 font-weight-600 text-323232 text-center pb-1 mb-sm-4 mt-md-3" data-aos="fade-up" data-aos-delay="300">ABOUT MORE GROUP</h2>
                        <hr>
                        <div class="kanit font-weight-600 font-22 text-323232 text-center pt-2 mt-sm-4" data-aos="fade-up" data-aos-delay="500">DUROFIX™ BELONGS TO THE REGITAR POWER TOOLS DIVISIONOF THE MORE GROUP.</div>
                        <div class="groupData" data-aos="fade-up" data-aos-delay="500">
                            <div class="dataItem"><span class="text-323232 font-weight-700 les05">FOUNDED: </span>1982</div>
                            <div class="dataItem"><span class="text-323232 font-weight-700 les05">EMPLOYEES: </span>1,800</div>
                            <div class="dataItem"><span class="text-323232 font-weight-700 les05">MAJOR PRODUCTS: </span>Power Tools, Automotive Electronics</div>
                        </div>
                        <div class="timelineBlock">
                            <div class="timelineInner">
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                        <img src="@Url.Content("~/styles/images/about/group01.jpg")" alt="">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">1982</h3>
                                            <div class="location">Mobiletron HQ (Taiwan), Taichung</div>
                                        </div>
                                        <div class="mobileImgBox">
                                            <img src="@Url.Content("~/styles/images/about/group01.jpg")" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                        <img src="@Url.Content("~/styles/images/about/group02.jpg")" alt="">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">1988</h3>
                                            <div class="location">Regitar USA (USA), Montgomery, AL</div>
                                        </div>
                                        <div class="mobileImgBox">
                                            <img src="@Url.Content("~/styles/images/about/group02.jpg")" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                        <img src="@Url.Content("~/styles/images/about/group03.jpg")" alt="">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">1995</h3>
                                            <div class="location">Mobiletron Ningbo (China), Ningbo</div>
                                        </div>
                                        <div class="mobileImgBox">
                                            <img src="@Url.Content("~/styles/images/about/group03.jpg")" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                        <img src="@Url.Content("~/styles/images/about/group04.jpg")" alt="">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">2000</h3>
                                            <div class="location">Mobiletron UK (UK), Preston</div>
                                        </div>
                                        <div class="mobileImgBox">
                                            <img src="@Url.Content("~/styles/images/about/group04.jpg")" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">2001</h3>
                                            <div class="location">Public (IPO) Company in Taiwan</div>
                                        </div>
                                        <div class="mobileImgBox">
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">2006</h3>
                                            <div class="location">TS16949 Certified</div>
                                        </div>
                                        <div class="mobileImgBox">
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                        <img src="@Url.Content("~/styles/images/about/group05.jpg")" alt="">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">2009</h3>
                                            <div class="location">Durofix Inc. (USA) Los Angeles, CA</div>
                                        </div>
                                        <div class="mobileImgBox">
                                            <img src="@Url.Content("~/styles/images/about/group05.jpg")" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="item">
                                    <div class="imgBox" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                                        <img src="@Url.Content("~/styles/images/about/group06.jpg")" alt="">
                                    </div>
                                    <div class="timeBox">
                                        <div class="time">
                                            <h3 class="year font-36 text-323232 font-weight-600 kanit">2018</h3>
                                            <div class="location">RAC (Taiwan), Taichung</div>
                                        </div>
                                        <div class="mobileImgBox">
                                            <img src="@Url.Content("~/styles/images/about/group06.jpg")" alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>*@
            </div>
        </div>
    </main>
</div>

m000355/Views/About/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wp" id="index">
    <main class="main brand">
        <div id="brand">
            <div class="pageBannerBlock blank" style="background-image: url(styles/images/about/about-banner.jpg);">
                <div class="breadcrumbInner">
                    <ol class="breadcrumb kanit font-weight-400">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">@ViewBag.ResLang["homepage"]</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "About")">@ViewBag.ResLang["aboutus"]</a></li>
                        <li class="breadcrumb-item" aria-current="page">@ViewBag.ResLang["footerbrand"]</li>
                    </ol>
                </div>
                <div class="pageTitle">
                    <h1 class="kanit font-80 font-weight-600" data-aos="fade-up">@ViewBag.ResLang["aboutus"]</h1>
                </div>
                <div class="tagsWrap kanit font-weight-600 font-18 unblank">
                    <div class="tagBox active">
                        <a href="@Url.Action("Index", "About")">@ViewBag.ResLang["footerbrand"]</a>
                    </div>
                    <div class="tagBox">
                        <a href="@Url.Action("Group", "About")">@ViewBag.ResLang["aboutmoregroup"]</a>
                    </div>
                </div>
            </div>
            <div class="brandMainBlock blank">
                @if (ViewBag.brandData != null)
                {
                    @Html.Raw(ViewBag.brandData)
                }
            </div>
        </div>
    </main>
</div>