m000355/Models/news.cs
namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public class news
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(64)]
        public string guid { get; set; }

        [StringLength(64)]
        public string category { get; set; }

        public string title { get; set; }

        public string subtitle { get; set; }

        public string content { get; set; }
        public string homedesc { get; set; }

        public DateTime? startdate { get; set; }

        public DateTime? enddate { get; set; }

        public DateTime? create_date { get; set; }

        public DateTime? modifydate { get; set; }
        public string create_name { get; set; }
        public string modify_name { get; set; }

        [StringLength(1)]
        public string sticky { get; set; }

        [StringLength(1)]
        public string index_sticky { get; set; }

        [StringLength(1)]
        public string status { get; set; }

        public string pic { get; set; }

        public string pic_alt { get; set; }

        [StringLength(30)]
        public string lang { get; set; }
        public string facebook { get; set; }
        public string line { get; set; }
        public string twitter { get; set; }
        public string keywords { get; set; }

        public string description { get; set; }
    }
}

m000355/Controllers/NewsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Models;
using Web.Models;
using Web.Service;

namespace m000355.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index(int? page)
        {
            if (Session["WordLang"] == null)
            {
                Session["WordLang"] = "en";
                Session["WholeLang"] = "EN";
            }

            string wholeLang = Session["WordLang"].ToString();
            if (wholeLang == null)
            {
                wholeLang = "en";
            }

            Model DB = new Model();

            var privacyData = (from a in DB.web_data
                               where a.lang == wholeLang
                               select a).FirstOrDefault();
            ViewBag.privacyData = privacyData.privacypolicy;

            if (privacyData != null)
            {
                ViewBag.description = privacyData.description_news;
                ViewBag.keywords = privacyData.keywords_news;
            }
            else
            {
                ViewBag.description = "";
                ViewBag.keywords = "";
            }

            var now = DateTime.Now;
            //var newsData = DB.news.Where(x => x.lang == wholeLang && x.status == "Y" && x.category == "22021014324219"
            //                                  && x.startdate <= now && ((x.enddate != null && x.enddate >= now) || x.enddate == null))
            //                                  .OrderByDescending(x => x.sticky).ThenByDescending(x => x.startdate).ThenByDescending(x => x.create_date).ToList();
            var newsData = DB.news.Where(x => x.lang == wholeLang && x.status == "Y"
                                  && x.startdate <= now && ((x.enddate != null && x.enddate >= now) || x.enddate == null))
                                  .OrderByDescending(x => x.sticky).ThenByDescending(x => x.startdate).ThenByDescending(x => x.create_date).ToList();

            ViewBag.newsData = newsData;
            if (newsData != null && newsData.Count != 0)
            {
                var pageNumber = page ?? 1;
                var pageSize = 8;
                ViewBag.NewsPageList = newsData.ToPagedList(pageNumber, pageSize);
                int Allpage = Convert.ToInt16(Math.Ceiling((double)newsData.Count / pageSize));
                ViewBag.pageView = FunctionService.getPageNumNoCatalog(Url.Content("~/") + "news?", Allpage, pageNumber, newsData.Count, "");
            }

            var productSubclassFirst = (from a in DB.product_subclass
                                        where a.status == "Y" && a.lang == wholeLang && a.category == "0"
                                        select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productSubclassFirst = productSubclassFirst;

            var productSubclassMultiLevel = (from a in DB.product_subclass
                                             where a.status == "Y" && a.lang == wholeLang && a.category != "0"
                                             select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productSubclassMultiLevel = productSubclassMultiLevel;

            var webBasicData = (from a in DB.web_data
                                where a.lang == wholeLang
                                select a).FirstOrDefault();
            ViewBag.webBasicData = webBasicData;

            var defaultcatalogguid = (from a in DB.dealer_catalog
                                      where a.lang == wholeLang && a.status == "Y"
                                      select a).OrderBy(x => x.sortIndex).ToList();

            NameValueCollection langData = new NameValueCollection();
            if (wholeLang == "tw")
            {
                langData = FunctionService.getLangData("tw");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "特色";
                //ViewBag.specificationsTab = "規格";
                //ViewBag.downloadTab = "下載";
                //ViewBag.searchkeyword = "關鍵字...";
                //ViewBag.searchResults = "個結果被找到關於";
                //ViewBag.searchAbout = "大約";
                //ViewBag.openRfq = "前往詢價";
                //ViewBag.saveRfq = "儲存詢價";
                //ViewBag.productsSearch = "產品搜尋";
                ViewBag.lang = "tw";
                //ViewBag.reqRfq = "詢價";
                //ViewBag.aboutus = "關於我們";
                //ViewBag.productpage = "產品專區";
                //ViewBag.warranty = "保修專區";
                //ViewBag.contactus = "聯絡我們";
                //ViewBag.catalogdownload = "型錄下載";
                //ViewBag.dealer = "經銷商區";
                //ViewBag.latestnews = "最新消息";
                //ViewBag.readmore = "瀏覽更多";
                //ViewBag.privacyPolicy = "隱私政策";
                //ViewBag.quotation = "詢問表單";
                //ViewBag.productDesc = "DUROFIX是21世紀的新品牌，目前正在歐洲、美洲、澳大利亞和亞洲推廣。";
                //ViewBag.homepage = "首頁";
                //ViewBag.productCategoryBtn = "產品類別";
                //ViewBag.productListBtn = "產品列表";
                //ViewBag.productSearchBtn = "產品搜尋";
                //ViewBag.terms = "條款";
                //ViewBag.registered = "商標";
                //ViewBag.inquire = "詢問";
                //ViewBag.information = "資訊";
                //ViewBag.contactform = "聯絡表單";
                //ViewBag.footerbrand = "品牌";
                //ViewBag.footergroup = "群組";
                //ViewBag.whychose = "為何選擇";
                //ViewBag.offlinepage = "網站維護中";
                //ViewBag.offlinemobilepage = "頁面維護中，請於稍後重整頁面";
                //ViewBag.completeall = "請填寫所有項目";
                //ViewBag.assure = "以確保正確回復";
                //ViewBag.businessType = "商業類型";
                //ViewBag.companyName = "公司名稱";
                //ViewBag.contactName = "聯絡人";
                //ViewBag.email = "電子郵件";
                //ViewBag.tel = "電話";
                //ViewBag.country = "國家";
                //ViewBag.address = "地址";
                //ViewBag.website = "網址";
                //ViewBag.subject = "主題";
                //ViewBag.leaveMessage = "留下您的訊息";
                //ViewBag.verification = "驗證碼";
                //ViewBag.submit = "提交";
                //ViewBag.previousbtn = "上一則";
                //ViewBag.nextbtn = "下一則";
                //ViewBag.backbtn = "回前頁";
            }
            else if (wholeLang == "en")
            {
                langData = FunctionService.getLangData("en");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "Features";
                //ViewBag.specificationsTab = "Specifications";
                //ViewBag.downloadTab = "Download";
                //ViewBag.searchkeyword = "Keyword...";
                //ViewBag.searchResults = " results found for ";
                //ViewBag.searchAbout = "About";
                //ViewBag.openRfq = "OPEN RFQ";
                //ViewBag.saveRfq = "Saved to Request for Quotation";
                //ViewBag.productsSearch = "Products Search";
                ViewBag.lang = "en";
                //ViewBag.reqRfq = "REQUEST FOR QUOTATION";
                //ViewBag.aboutus = "ABOUT US";
                //ViewBag.productpage = "PRODUCTS";
                //ViewBag.warranty = "WARRANTY";
                //ViewBag.contactus = "CONTACT US";
                //ViewBag.catalogdownload = "CATALOG DOWNLOAD";
                //ViewBag.dealer = "DEALER";
                //ViewBag.latestnews = "LATEST NEWS";
                //ViewBag.readmore = "READ MORE";
                //ViewBag.privacyPolicy = "PRIVACY POLICY";
                //ViewBag.quotation = "Request for Quotation";
                //ViewBag.productDesc = "DUROFIX™ is a new brand for the 21st century, and is currently being promoted in Europe, America, Australia, and Asia.";
                //ViewBag.homepage = "HOME";
                //ViewBag.productCategoryBtn = "Product Category";
                //ViewBag.productListBtn = "Product List";
                //ViewBag.productSearchBtn = "PRODUCT SEARCH";
                //ViewBag.terms = "TERMS";
                //ViewBag.registered = "REGISTERED";
                //ViewBag.inquire = "INQUIRE";
                //ViewBag.information = "INFORMATION";
                //ViewBag.contactform = "CONTACT FORM";
                //ViewBag.footerbrand = "BRAND";
                //ViewBag.footergroup = "GROUP";
                //ViewBag.whychose = "WHY CHOOSE DUROFIX";
                //ViewBag.offlinepage = "The Website is Under Maintenance";
                //ViewBag.offlinemobilepage = "This page is down for maintenance. We are working to get it back up and running as soon as possible. Please check back!";
                //ViewBag.completeall = "Please complete all item with";
                //ViewBag.assure = "to assure proper response";
                //ViewBag.businessType = "Business Type";
                //ViewBag.companyName = "Company Name";
                //ViewBag.contactName = "Contact Name";
                //ViewBag.email = "E-mail";
                //ViewBag.tel = "TEL";
                //ViewBag.country = "Country";
                //ViewBag.address = "Address";
                //ViewBag.website = "Web Site";
                //ViewBag.subject = "Subject";
                //ViewBag.leaveMessage = "Leave Your Message";
                //ViewBag.verification = "Verification code";
                //ViewBag.submit = "SUBMIT";
                //ViewBag.previousbtn = "Previous";
                //ViewBag.nextbtn = "Next";
                //ViewBag.backbtn = "Back";
            }
            else if (wholeLang == "cn")

m000355/Views/News/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wp" id="index">
    <main class="main news">
        <div id="news">
            <div class="pageBannerBlock blank" style="background-image: url(styles/images/news/news-banner.jpg);">
                <div class="breadcrumbInner">
                    <ol class="breadcrumb kanit font-weight-400">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">@ViewBag.ResLang["homepage"]</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "News")">@ViewBag.ResLang["latestnews"]</a></li>
                        @*<li class="breadcrumb-item" aria-current="page">ALL</li>*@
                    </ol>
                </div>
                <div class="pageTitle">
                    <h1 class="kanit font-80 font-weight-600" data-aos="fade-up">@ViewBag.ResLang["latestnews"]</h1>
                </div>
            </div>
            <div class="newsMainBlock blank">
                <div class="newsMainInner">
                    <div class="newsList" data-aos="fade-up" data-aos-delay="300" data-aos-duration="800">
                        @if (ViewBag.NewsPageList != null)
                        {
                            foreach (var item in ViewBag.NewsPageList)
                            {
                                <h2 class="d-none">@item.title</h2>
                                <a href="@Url.Action("New", "News", new { guid = item.guid})" class="newsItem d-block">
                                    <span class="imgBox d-block">
                                        <img src="@Url.Content("~" + item.pic)" alt="">
                                    </span>
                                    <span class="newsTitle kanit font-18 font-weight-600 text-323232 text-center d-block">@item.subtitle</span>
                                    <span class="date kanit font-16 text-center text-969696 d-block">@item.startdate.Year/@item.startdate.Month/@item.startdate.Day</span>
                                </a>
                            }
                        }

                    </div>
                    <div class="pagination d-flex flex-justify-center">
                        @Html.Raw(ViewBag.pageView)
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

m000355/Views/News/New.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wp" id="index">
    <main class="main new">
        <div id="new">
            <div class="pageBannerBlock blank" style="background-image: url(@Url.Content("~/styles/images/news/news-banner.jpg"));">
                <div class="breadcrumbInner">
                    <ol class="breadcrumb kanit font-weight-400">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">@ViewBag.ResLang["homepage"]</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "News")">@ViewBag.ResLang["latestnews"]</a></li>
                        @*<li class="breadcrumb-item" aria-current="page">ALL</li>*@
                    </ol>
                </div>
                <div class="pageTitle">
                    <h1 class="kanit font-80 font-weight-600" data-aos="fade-up">@ViewBag.ResLang["latestnews"]</h1>
                </div>
            </div>
            <div class="newMainBlock blank">
                <div class="newMainInner">
                    <div class="titleWrap" data-aos="fade-up" data-aos-delay="300">
                        <div class="shareWrap">
                            @*@if (ViewBag.newData.facebook != "")
                                {
                                    <a href="@ViewBag.newData.facebook" class="iconBox"><i class="icon-fb"></i></a>
                                }
                                else
                                {
                                    <a href="" class="iconBox"><i class="icon-fb"></i></a>
                                }
                                @if (ViewBag.newData.twitter != "")
                                {
                                    <a href="@ViewBag.newData.twitter" class="iconBox"><i class="icon-twitter"></i></a>
                                }
                                else
                                {
                                    <a href="" class="iconBox"><i class="icon-twitter"></i></a>
                                }
                                @if (ViewBag.newData.line != "")
                                {
                                    <a href="@ViewBag.newData.line" class="iconBox"><i class="icon-line"></i></a>
                                }
                                else
                                {
                                    <a href="" class="iconBox"><i class="icon-line"></i></a>
                                }*@
                            <a href="javascript:void(0)" id="fb_s" class="iconBox" target="_blank"><i class="icon-fb"></i></a>
                            <a href="javascript:void(0)" id="tt_s" class="iconBox"><i class="icon-twitter"></i></a>
                            <a href="javascript:void(0)" id="line_s" class="iconBox"><i class="icon-line"></i></a>
                        </div>
                        <h2 class="mainTitle kanit font-30 font-weight-600 text-323232 text-center" data-aos="fade-up" data-aos-delay="500">@ViewBag.newData.title</h2>
                        <div class="date kanit font-16 text-969696 text-center" data-aos="fade-up" data-aos-delay="500">@ViewBag.newData.startdate.Year/@ViewBag.newData.startdate.Month/@ViewBag.newData.startdate.Day</div>
                    </div>
                    <div class="editor" data-aos="fade-up" data-aos-delay="800" data-aos-duration="800">
                        @if (ViewBag.newData.content != null)
                        {
                            if (ViewBag.newData.content == "")
                            {

                            }
                            else
                            {
                                @Html.Raw(ViewBag.newData.content)
                            }
                        }
                    </div>
                    <div class="pageNavWrap font-16 kanit text-646464">
                        <div class="navBox" data-aos="fade-left" data-aos-delay="500" data-aos-duration="700">
                            <a href="@Url.Action("New", "News", new { guid = ViewBag.prevNews.guid})" class="prevBtn">
                                <i class="icon-arrow text-FCAE07"></i>
                                <span>@ViewBag.ResLang["previousbtn"]</span>
                            </a>
                        </div>
                        <div class="navBox" data-aos="flip-right" data-aos-delay="300">
                            <a href="@Url.Action("Index", "News")" class="backBtn">
                                <span>@ViewBag.ResLang["backbtn"]</span>
                            </a>
                        </div>
                        <div class="navBox" data-aos="fade-right" data-aos-delay="500" data-aos-duration="700">
                            <a href="@Url.Action("New", "News", new { guid = ViewBag.nextNews.guid})" class="nextBtn">
                                <span>@ViewBag.ResLang["nextbtn"]</span>
                                <i class="icon-arrow text-FCAE07"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            //FB分享
            $("#fb_s").click(function (e) {
                var thisURL = window.document.location.href;
                console.log(thisURL);
                window.open('http://www.facebook.com/share.php?u='.concat(thisURL), 'pop', config = 'height=500,width=500');
            });

            //twitter分享
            $("#tt_s").click(function (e) {
                var pageTitle = encodeURIComponent(document.title);
                var thisURL = window.document.location.href;
                window.open('http://twitter.com/home?status=' + pageTitle + "+".concat(thisURL), 'pop', config = 'height=500,width=500');
            });

            //line分享
            $("#line_s").click(function (e) {
                var pageTitle = encodeURIComponent(document.title);
                var thisURL = encodeURIComponent(window.document.location.href);
                // window.open('http://line.naver.jp/R/msg/text/?' + "+".concat(thisURL), 'pop', config = 'height=500,width=500');

                window.open('https://social-plugins.line.me/lineit/share?url=' + thisURL, 'pop', config = 'height=500,width=500');
            });


            //重製驗證碼

            $('#captcha').click(function () {

                var src = $('#captcha').attr('src').split('?');

                $('#captcha').attr('src', src[0] + "?d=" + Date.now());

            });
        });
    </script>
}