m000355/Models/contactinfo.cs
namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public class contactinfo
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(64)]
        public string guid { get; set; }

        public string businesstype { get; set; }
        public string companyname { get; set; }
        public string contactname { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string website { get; set; }
        public string subject { get; set; }
        public string message { get; set; }

        [StringLength(1)]
        public string status { get; set; }
        public DateTime? create_date { get; set; }

        public DateTime? modifydate { get; set; }
        public string create_name { get; set; }
        public string modify_name { get; set; }

        [StringLength(30)]
        public string lang { get; set; }
    }
}

m000355/Models/service.cs
namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public class service
    {
        [Key]
        [Column(Order = 0)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        [Key]
        [Column(Order = 1)]
        [StringLength(64)]
        public string guid { get; set; }

        public string title { get; set; }
        public string subtitle { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string address { get; set; }

        [StringLength(1)]
        public string status { get; set; }
        public DateTime? create_date { get; set; }

        public DateTime? modifydate { get; set; }
        public string create_name { get; set; }
        public string modify_name { get; set; }

        [StringLength(30)]
        public string lang { get; set; }
        public string maparea { get; set; }
        public string mapsitex { get; set; }

        public string mapsitey { get; set; }
    }
}

m000355/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Models;
using web.Models.ViewModels;
using Web.Models;
using Web.Service;

namespace m000355.Controllers
{
    public class ServiceController : Controller
    {
        // GET: Service
        public ActionResult Index()
        {
            if (Session["WordLang"] == null)
            {
                Session["WordLang"] = "en";
                Session["WholeLang"] = "EN";
            }

            string wholeLang = Session["WordLang"].ToString();
            if (wholeLang == null)
            {
                wholeLang = "en";
            }

            Model DB = new Model();

            var privacyData = (from a in DB.web_data
                               where a.lang == wholeLang
                               select a).FirstOrDefault();
            ViewBag.privacyData = privacyData.privacypolicy;

            var productSubclassFirst = (from a in DB.product_subclass
                                        where a.status == "Y" && a.lang == wholeLang && a.category == "0"
                                        select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productSubclassFirst = productSubclassFirst;

            var productSubclassMultiLevel = (from a in DB.product_subclass
                                             where a.status == "Y" && a.lang == wholeLang && a.category != "0"
                                             select a).OrderBy(x => x.sortIndex).ToList();
            ViewBag.productSubclassMultiLevel = productSubclassMultiLevel;

            var webBasicData = (from a in DB.web_data
                                where a.lang == wholeLang
                                select a).FirstOrDefault();
            ViewBag.webBasicData = webBasicData;

            var defaultcatalogguid = (from a in DB.dealer_catalog
                                      where a.lang == wholeLang && a.status == "Y"
                                      select a).OrderBy(x => x.sortIndex).ToList();

            NameValueCollection langData = new NameValueCollection();
            if (wholeLang == "tw")
            {
                langData = FunctionService.getLangData("tw");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "特色";
                //ViewBag.specificationsTab = "規格";
                //ViewBag.downloadTab = "下載";
                //ViewBag.searchkeyword = "關鍵字...";
                //ViewBag.searchResults = "個結果被找到關於";
                //ViewBag.searchAbout = "大約";
                //ViewBag.openRfq = "前往詢價";
                //ViewBag.saveRfq = "儲存詢價";
                //ViewBag.productsSearch = "產品搜尋";
                ViewBag.lang = "tw";
                //ViewBag.reqRfq = "詢價";
                //ViewBag.aboutus = "關於我們";
                //ViewBag.productpage = "產品專區";
                //ViewBag.warranty = "保修專區";
                //ViewBag.contactus = "聯絡我們";
                //ViewBag.catalogdownload = "型錄下載";
                //ViewBag.dealer = "經銷商區";
                //ViewBag.latestnews = "最新消息";
                //ViewBag.readmore = "瀏覽更多";
                //ViewBag.privacyPolicy = "隱私政策";
                //ViewBag.quotation = "詢問表單";
                //ViewBag.productDesc = "DUROFIX是21世紀的新品牌，目前正在歐洲、美洲、澳大利亞和亞洲推廣。";
                //ViewBag.homepage = "首頁";
                //ViewBag.productCategoryBtn = "產品類別";
                //ViewBag.productListBtn = "產品列表";
                //ViewBag.productSearchBtn = "產品搜尋";
                //ViewBag.terms = "條款";
                //ViewBag.registered = "商標";
                //ViewBag.inquire = "詢問";
                //ViewBag.information = "資訊";
                //ViewBag.contactform = "聯絡表單";
                //ViewBag.footerbrand = "品牌";
                //ViewBag.footergroup = "群組";
                //ViewBag.whychose = "為何選擇";
                //ViewBag.offlinepage = "網站維護中";
                //ViewBag.offlinemobilepage = "頁面維護中，請於稍後重整頁面";
                //ViewBag.completeall = "請填寫所有項目";
                //ViewBag.assure = "以確保正確回復";
                //ViewBag.businessType = "商業類型";
                //ViewBag.companyName = "公司名稱";
                //ViewBag.contactName = "聯絡人";
                //ViewBag.email = "電子郵件";
                //ViewBag.tel = "電話";
                //ViewBag.country = "國家";
                //ViewBag.address = "地址";
                //ViewBag.website = "網址";
                //ViewBag.subject = "主題";
                //ViewBag.leaveMessage = "留下您的訊息";
                //ViewBag.verification = "驗證碼";
                //ViewBag.submit = "提交";
                //ViewBag.contactinfo = "聯絡資訊";
                //ViewBag.contactservice = "服務";
            }
            else if (wholeLang == "en")
            {
                langData = FunctionService.getLangData("en");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "Features";
                //ViewBag.specificationsTab = "Specifications";
                //ViewBag.downloadTab = "Download";
                //ViewBag.searchkeyword = "Keyword...";
                //ViewBag.searchResults = " results found for ";
                //ViewBag.searchAbout = "About";
                //ViewBag.openRfq = "OPEN RFQ";
                //ViewBag.saveRfq = "Saved to Request for Quotation";
                //ViewBag.productsSearch = "Products Search";
                ViewBag.lang = "en";
                //ViewBag.reqRfq = "REQUEST FOR QUOTATION";
                //ViewBag.aboutus = "ABOUT US";
                //ViewBag.productpage = "PRODUCTS";
                //ViewBag.warranty = "WARRANTY";
                //ViewBag.contactus = "CONTACT US";
                //ViewBag.catalogdownload = "CATALOG DOWNLOAD";
                //ViewBag.dealer = "DEALER";
                //ViewBag.latestnews = "LATEST NEWS";
                //ViewBag.readmore = "READ MORE";
                //ViewBag.privacyPolicy = "PRIVACY POLICY";
                //ViewBag.quotation = "Request for Quotation";
                //ViewBag.productDesc = "DUROFIX™ is a new brand for the 21st century, and is currently being promoted in Europe, America, Australia, and Asia.";
                //ViewBag.homepage = "HOME";
                //ViewBag.productCategoryBtn = "Product Category";
                //ViewBag.productListBtn = "Product List";
                //ViewBag.productSearchBtn = "PRODUCT SEARCH";
                //ViewBag.terms = "TERMS";
                //ViewBag.registered = "REGISTERED";
                //ViewBag.inquire = "INQUIRE";
                //ViewBag.information = "INFORMATION";
                //ViewBag.contactform = "CONTACT FORM";
                //ViewBag.footerbrand = "BRAND";
                //ViewBag.footergroup = "GROUP";
                //ViewBag.whychose = "WHY CHOOSE DUROFIX";
                //ViewBag.offlinepage = "The Website is Under Maintenance";
                //ViewBag.offlinemobilepage = "This page is down for maintenance. We are working to get it back up and running as soon as possible. Please check back!";
                //ViewBag.completeall = "Please complete all item with";
                //ViewBag.assure = "to assure proper response";
                //ViewBag.businessType = "Business Type";
                //ViewBag.companyName = "Company Name";
                //ViewBag.contactName = "Contact Name";
                //ViewBag.email = "E-mail";
                //ViewBag.tel = "TEL";
                //ViewBag.country = "Country";
                //ViewBag.address = "Address";
                //ViewBag.website = "Web Site";
                //ViewBag.subject = "Subject";
                //ViewBag.leaveMessage = "Leave Your Message";
                //ViewBag.verification = "Verification code";
                //ViewBag.submit = "SUBMIT";
                //ViewBag.contactinfo = "CONTACT INFO.";
                //ViewBag.contactservice = "SERVICE";
            }
            else if (wholeLang == "cn")
            {
                langData = FunctionService.getLangData("cn");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                if (defaultcatalogguid.Count() == 0)
                {
                    ViewBag.defaultcatalogguid = "";
                }
                else
                {
                    ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                }

                ViewBag.lang = "cn";
            }
            else
            {
                langData = FunctionService.getLangData("en");//取得語系檔案
                ViewBag.ResLang = langData;//取得語系檔案

                ViewBag.defaultcatalogguid = defaultcatalogguid[0].guid;
                //ViewBag.featuresTab = "Features";
                //ViewBag.specificationsTab = "Specifications";
                //ViewBag.downloadTab = "Download";
                //ViewBag.searchkeyword = "Keyword...";
                //ViewBag.searchResults = " results found for ";
                //ViewBag.searchAbout = "About";
                //ViewBag.openRfq = "OPEN RFQ";
                //ViewBag.saveRfq = "Saved to Request for Quotation";
                //ViewBag.productsSearch = "Products Search";
                ViewBag.lang = "en";
                //ViewBag.reqRfq = "REQUEST FOR QUOTATION";
                //ViewBag.aboutus = "ABOUT US";
                //ViewBag.productpage = "PRODUCTS";
                //ViewBag.warranty = "WARRANTY";
                //ViewBag.contactus = "CONTACT US";
                //ViewBag.catalogdownload = "CATALOG DOWNLOAD";
                //ViewBag.dealer = "DEALER";
                //ViewBag.latestnews = "LATEST NEWS";
                //ViewBag.readmore = "READ MORE";

m000355/Views/Service/Contactinfo.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="wp" id="index">
    <main class="main contact">
        <div id="contact">
            <div class="pageBannerBlock blank" style="background-image: url(@Url.Content("~/styles/images/contact/contact-banner.jpg"));">
                <div class="breadcrumbInner">
                    <ol class="breadcrumb kanit font-weight-400">
                        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">@ViewBag.ResLang["homepage"]</a></li>
                        <li class="breadcrumb-item"><a href="@Url.Action("Contactus", "Service")">@ViewBag.ResLang["contactus"]</a></li>
                        <li class="breadcrumb-item" aria-current="page">@ViewBag.ResLang["contactinfo"]</li>
                    </ol>
                </div>
                <div class="pageTitle">
                    <h1 class="kanit font-80 font-weight-600" data-aos="fade-up">@ViewBag.ResLang["contactus"]</h1>
                </div>
                <div class="tagsWrap kanit font-weight-600 font-18 unblank">
                    <div class="tagBox">
                        <a href="@Url.Action("Contactus", "Service")">@ViewBag.ResLang["contactservice"]</a>
                    </div>
                    <div class="tagBox active">
                        <a href="@Url.Action("Contactinfo", "Service")">@ViewBag.ResLang["contactinfo"]</a>
                    </div>
                </div>
            </div>
            <div class="contactMainBlock blank">
                <h2 class="mainTitle kanit font-30 font-weight-600 text-323232 text-center" data-aos="fade-up" data-aos-delay="300">@ViewBag.ResLang["contactinfo"]</h2>
                <div class="contactMainInner text-646464 roboto font-16">
                    <div class="RFQFormBox" data-aos="fade-up" data-aos-delay="500" data-aos-duration="600">
                        <div class="hint kanit text-323232 font-18">@ViewBag.ResLang["completeall"] <span class="text-red">*</span> @ViewBag.ResLang["assure"]</div>
                        <form action="@Url.Content("~/service/Send")" method="post" id="contactForm" class="RFQForm">
                            @Html.AntiForgeryToken()
                            @if (ViewBag.lang == "en")
                            {
                                <div class="field-group">
                                    <label class="label" for="bType">@ViewBag.ResLang["businessType"] <span class="text-red">*</span></label>
                                    <select class="selectpicker" id="bType" name="bType">
                                        @if (ViewBag.contactSubjectData != null)
                                        {
                                            foreach (var item in ViewBag.contactSubjectData)
                                            {
                                                <option>@item</option>
                                            }
                                        }
                                    </select>
                                </div>
                            }

                            <div class="field-group half">
                                <label class="label" for="corp">@ViewBag.ResLang["companyName"] <span class="text-red">*</span></label>
                                <input class="input" type="text" id="corp" name="corp" required>
                            </div>
                            <div class="field-group half">
                                <label class="label" for="name">@ViewBag.ResLang["contactName"] <span class="text-red">*</span></label>
                                <input class="input" type="text" id="name" name="name" required>
                            </div>
                            <div class="field-group half">
                                <label class="label" for="email">@ViewBag.ResLang["email"] <span class="text-red">*</span></label>
                                <input class="input" type="email" id="email" name="email" required>
                            </div>
                            <div class="field-group half">
                                <label class="label" for="tel">@ViewBag.ResLang["tel"] <span class="text-red">*</span></label>
                                <input class="input" type="tel" id="tel" name="tel" required>
                            </div>
                            @if (ViewBag.lang == "en")
                            {
                                <div class="field-group p350">
                                    <label class="label" for="country">@ViewBag.ResLang["country"] <span class="text-red">*</span></label>
                                    <select class="selectpicker" id="country" name="country">
                                        @if (ViewBag.contactCountryData != null)
                                        {
                                            foreach (var item in ViewBag.contactCountryData)
                                            {
                                                <option>@item</option>
                                            }
                                        }
                                    </select>
                                </div>
                                <div class="field-group p640">
                                    <label class="label" for="adress">@ViewBag.ResLang["address"]</label>
                                    <input class="input" type="text" id="adress" name="adress">
                                </div>
                                <div class="field-group">
                                    <label class="label" for="web">@ViewBag.ResLang["website"]</label>
                                    <input class="input" type="text" id="web" name="web">
                                </div>
                            }

                            <div class="field-group">
                                <label class="label" for="subject">@ViewBag.ResLang["subject"] <span class="text-red">*</span></label>
                                @*<select class="selectpicker" id="subject" name="subject">
                                        @if (ViewBag.contactSubjectData != null)
                                        {
                                            foreach (var item in ViewBag.contactSubjectData)
                                            {
                                                <option>@item</option>
                                            }
                                        }
                                    </select>*@
                                <input class="input" type="text" id="subject" name="subject">
                            </div>
                            <div class="field-group textareaGroup">
                                <label class="label textareaLabel" for="content">@ViewBag.ResLang["leaveMessage"]</label>
                                <textarea class="input textarea" id="content" name="content" placeholder=""></textarea>
                            </div>
                            <div class="field-group p445">
                                <label class="label" for="vcode">@ViewBag.ResLang["verification"] <span class="text-red">*</span></label>
                                <input class="input" type="text" id="vcode" name="vcode" required>
                            </div>
                            <div class="v-code">
                                <img id="captcha" onclick="reloadCaptcha()" src="@Url.Content("~/Content/BuildCaptcha.aspx")" alt="">
                            </div>
                            <div class="submitWrap">
                                <button class="submit flex-center kanit font-18 font-weight-500" type="submit">
                                    <span class="d-block">@ViewBag.ResLang["submit"]</span>
                                </button>
                            </div>
                        </form>
                    </div>

                    @if (TempData["alertmessage"] != null)
                    {
                        <script type="text/javascript">
        var message = @Html.Raw(Json.Encode(TempData["alertmessage"]));
        alert(message);
                        </script>
                    }

                </div>
            </div>
        </div>
    </main>
</div>

@section scripts
{
    <script type="text/javascript">
        //重製驗證碼
        function reloadCaptcha() {
            $('#captcha').attr('src', $('#captcha').attr('src') + "?d=" + Date.now());
        }
    </script>
}